---
title: "Chinese fictions and films"
---

<style type="text/css">
.title {
  display: none;
}
img {
  border-radius: 200px 200px 200px 200px;
}

<<<<<<< Updated upstream
</style>


# Fictions

## 20th-century fictions (in order of publication)
=======
#Fictions in Chinese (in order of publication)


1. Eileen Chang 張愛玲, 第一爐香	1943	Chinese-Macanese	Eurasian

2. Eileen Chang 張愛玲, "Chained Links" 連環套 1944 Chinese-Indian	Chinese-British	Eurasian

3. Eileen Chang 張愛玲,紅玫瑰白玫瑰	1944	Chinese-British	Eurasian

4. 金庸，倚天屠龍記 1962 Eurasian Chinese-Iranian

5. 黃春明，小寡婦	1975	Afro-Asian	African American G.I. Babies

6. 陳映真，六月裏的玫瑰花	1978	Afro-Asian	African American	G.I. Babies

7. 黃碧雲，嘔吐	1994	Afro-Asian	African American	Hong Kong

8. 施叔青，她名叫蝴蝶/遍山洋紫荊/寂寞雲園  1993-1996 Chinese-British	Eurasian Hong Kong 

9. 嚴歌苓，小姨多鶴	2008	Chinese-Japanese	

10. 甘耀明，邦查女孩	2015	Afro-Austronesian	Indigenous Taiwan	African American G.I. Babies


## Films in Chinese

1. 客途秋恨 Song of the Exile 	1990	Chinese-Japanese	

2. 花街時代 My name ain't Suzie	1985	Chinese-American	G.I. Babies

3. 楊德昌，恐怖分子	1986	Chinese-American	G.I. Babies

4. 鄭有杰，陽陽	2009	French-Taiwanese	

5. 幸福路上	2017	Chinese-American	G.I. Babies

6. Laha Mebow，哈勇家	2022		

7. 林聖賢，爸爸歐巴馬	2023	Afro-Asian	African American

>>>>>>> Stashed changes




