---
title: "Collaborate"
---

<style type="text/css">
.title {
  display: none;
}
img {
  border-radius: 200px 200px 200px 200px;
}

</style>

# Instructions for collaborating

## Option A:

Submit to the database using [this form](https://forms.gle/Kc2bJCt6bTWLYGvP9)

Please also include your contact information so that we can credit your contribution!

## Option B:

Pre-requisites:

- GitHub Account and GitHub Desktop

- RStudio (and R)

Once you are added as a collaborator to the GitHub repo, you'll need to: 

1. Clone the repository (using GitHub Desktop) or `pull` any new updates. *Always `pull` before you start making any changes.*

2. Open up the `Mixed Race Lit.Rproj`

3. Add to the `films.Rmd` and `fictions.Rmd`, or edit whichever `.rmd` files need to be edited.

4. The database files are located in `resources/database.csv`, feel free to use your preferred editor to add or change any of the entries.

5. **Remember to** `knit` **any of the** `.rmd` **files that were edited.** Even if you just edited the `resources/database.csv` file, you still will need to `knit` the `search.rmd` file for the changes to be displayed.

6. `Push` the changes using GitHub Desktop!

Any changes may take a few minutes before the website is updated.


